### ISSUE TITLE
to onnx

### ISSUE THREAD

**Issue by kingvision** [sacmehta/EdgeNets#1]
I have tried to convert pytorch model to onnx with api (torch.onnx.export), but I meet a problem showing below info
Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible
How could I fix it ?

**Comment by sacmehta** [comment]
Which model in onnx are you looking for?

**Comment by sacmehta** [comment]
I have added ESPNetv2 onnx compatible models.

See here: https://github.com/sacmehta/EdgeNets/tree/master/onnx_models/classification/espnetv2

**Comment by kingvision** [comment]
thanks, Can you provide code to turn onnx? What I need is to train my own data model and then turn it into an onnx model.

**Comment by sacmehta** [comment]
Unfortunately, I cannot provide it now because we are checking its stability across different models. However, we will be releasing it sometime next month.

**Comment by kingvision** [comment]
I export an onnx model for segment, I got the follow error:
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

How i can fix it?

**Comment by pribadihcr** [comment]
+1
