### ISSUE TITLE
onnx model error

### ISSUE THREAD

**Issue by kingvision** [sacmehta/EdgeNets#15]
Hi 
   I got the follow error when i convert espnetv2 segment model to onnx.
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

how i can fix it?

**Comment by sacmehta** [comment]
Which model are you looking for?

**Comment by kingvision** [comment]
I used my own data to train the espnetv2 segment model, and the conversion to the onnx model failed. I used the pytorch1.2 and onnx1.5 version.
Can you tell me how you converted successfully? Which version of pytorch and onnx are you using?
Thank you

**Comment by sacmehta** [comment]
You need to make everything static for onnx conversion. We are writing a wrapper that convert our models, but that wrapper won’t be available soon.
