### ISSUE TITLE
Cityscapes class weightings do not correspond to my calculations

### ISSUE THREAD

**Issue by mitalbert** [sacmehta/EdgeNets#17]
Hi,

Below are the class weights of Cityscapes train dataset I have calculated, which are different from ones found in train_segmentation.py. Can you please share the formula/script for calculating the class weights?

0.0819
0.4754
0.1323
1.5207
1.5190
2.4737
8.1900
5.2310
0.1869
1.4687
0.6881
1.9825
7.8143
0.4165
1.3811
1.1989
0.6276
5.3559
4.0925

**Comment by sacmehta** [comment]
We used it from ERFNet. See here:

https://github.com/Chenfeng1271/erfnet_pytorch/blob/09efaac1dc7829e3719552cbe1e63183368f916d/train/main.py#L113
