### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Novabaideguo** [sacmehta/EdgeNets#2]
Sorry for disturbing you.
When I run the test_detection.py ,I got an error:RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float.
How can I solve it? Thank you

**Comment by sacmehta** [comment]
Let me check it. Meanwhile, you can use CUDA_VISIBLE_DEVICES=‘’. This will enforce your model to run on CPU.

**Comment by sacmehta** [comment]
Are you using torchvision version 0.3? If not, could you try with that?

**Comment by sacmehta** [comment]
I have fixed it. Please check
