### ISSUE TITLE
 How to do semantic segmentation of two categories ？

### ISSUE THREAD

**Issue by lighTQ** [sacmehta/EdgeNets#21]
(including background and palm)

I am using a dataset in pascal voc format, so I need to do extra opcodes besides modifying VOC_CLASS_LIST, and loss_type to bce

**Comment by sacmehta** [comment]
You can edit this custom file as per your need.

https://github.com/sacmehta/EdgeNets/blob/4aa09637ad4bc2337e887c3ff0633e819fb2bcde/data_loader/segmentation/custom_dataset_loader.py#L20
