### ISSUE TITLE
How to use the scripts to train the model with multiple loss?

### ISSUE THREAD

**Issue by monk42** [sacmehta/EdgeNets#26]
Hi sacmehta,
    I want to use the scripts to train the model with multiple loss, like PSPNet 's auxiliary loss. Can you give me some advices modify the scripts?

**Comment by sacmehta** [comment]
You need to make two changes:
i) Return multiple outputs from ESPNet forward function

https://github.com/sacmehta/EdgeNets/blob/096d165c305a1ebef8cb8ee0f38945e780ecc046/model/segmentation/espnetv2.py#L163

ii) Then compute the loss for multiple outputs here:

https://github.com/sacmehta/EdgeNets/blob/096d165c305a1ebef8cb8ee0f38945e780ecc046/utilities/train_eval_seg.py#L27
