### ISSUE TITLE
about recept_limit and replayers

### ISSUE THREAD

**Issue by lawo123** [sacmehta/EdgeNets#27]
I was looking at your code about segmentation recently.I want to ask you a question, why do you need to limit receptive field at each spatial level？
How to determine the value of rep_layers?
`rep_layers = [0, 3, 7, 3]

recept_limit = [13, 11, 9, 7, 5]`

**Comment by sacmehta** [comment]
# of block at each spatial level (Rep layer) values are taken from previous work (ShuffleNet).

Receptive field values at each spatial level are taken considering the spatial size and our previous work, ESPNet (ECCv).
