### ISSUE TITLE
the segmentation speed is too slow on Android

### ISSUE THREAD

**Issue by lawo123** [sacmehta/EdgeNets#28]
I deployed the segmentation model to android by ncnn,the inference cost 400ms,image_size=512*512.How to increase speed？

**Comment by sacmehta** [comment]
Are you running on CPU? Which task are you running? If its a detection task, you might want to use 300x300 resolution?

**Comment by lawo123** [comment]
I run segmentation task on Android gpu,scales = 2.My picture is 1024 ×720,so i pretrained model to 512*512 resolution.

**Comment by sacmehta** [comment]
Could you benchmark different stages (frame reading/processing, model execution, overlay etc.) to understand the bottleneck?

**Comment by sacmehta** [comment]
I think the issue is solved, so closing now
