### ISSUE TITLE
convert model to onnx and coreml [segmentation part]

### ISSUE THREAD

**Issue by sjf18** [sacmehta/EdgeNets#29]
hi, thanks  for your great work, could you please share your code for converting pytorch models of segmentation parts to onnx models and onnx to coreml, i have tried to convert on my own, but i get several errors.

**Comment by sacmehta** [comment]
Have you seen this thread?
 https://github.com/sacmehta/EdgeNets/issues/24#issuecomment-592138043

For CoreML-model, you can see: https://github.com/sacmehta/ESPNetv2-COREML

**Comment by sacmehta** [comment]
I assume this issue is fixed, so closing it now. Feel free to reopen if required
