### ISSUE TITLE
About computing fps

### ISSUE THREAD

**Issue by xzydxh** [sacmehta/EdgeNets#3]
Hello,I have trained the network with two GPUs and the batch_size=16. Batch_time=0.5 when  validation ，how can i compute fps.Thanks for your work.

**Comment by sacmehta** [comment]
See this thread.

https://github.com/sacmehta/ESPNet/issues/57

**Comment by xzydxh** [comment]
Thank you for your help.

**Comment by xzydxh** [comment]
Thank you for your help.
