### ISSUE TITLE
Failed to export an ONNX attribute 'onnx::Gather'

### ISSUE THREAD

**Issue by pribadihcr** [sacmehta/EdgeNets#32]
Hi @sacmehta,

I got the following error when convert the segmentation espnetv2 model to onnx:
(pytorch version: 1.4.0)
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by sacmehta** [comment]
see https://github.com/sacmehta/EdgeNets/issues/29#issuecomment-596712398

**Comment by sacmehta** [comment]
Please reopen if above mentioned link does not addresses your problem. Closing for now.
