### ISSUE TITLE
Model twice in README_Segmentation.md

### ISSUE THREAD

**Issue by mitalbert** [sacmehta/EdgeNets#36]
FYI, the model and s arguments are passed twice, so the arguments are getting overwritten.

> # Cityscapes dataset
> CUDA_VISIBLE_DEVICES=0 python train_segmentation.py --model espnetv2 --s 2.0 --dataset city --data-path ./vision_datasets/cityscapes/ --batch-size 25 --crop-size 512 256 --model dicenet --s 1.75 --lr 0.009 --scheduler hybrid --clr-max 61 --epochs 100

**Comment by sacmehta** [comment]
Thanks for noting it. I have fixed it.
