### ISSUE TITLE
Error on executing the Evaluation Command:

### ISSUE THREAD

**Issue by SaqibMamoon** [sacmehta/EdgeNets#5]
ERROR: `nofiles in the directory: ../vision_datasets/cityscapes/leftimg8bit/val/*/*.png`
ERROR: `Existing`

Please guide what should I do to resolve  the issue, although train command works fine, and I have done training.

**Comment by sacmehta** [comment]
Could you check if this directory exist? From error, it is clear that there are no files.

BTW, if you have followed our instructions for downloading the dataset, then files would be in ‘./vision_datasets’ folder and not in ../vision_datasets folder
